server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user_service:8000/
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/user/$\{segment}
            
        - id: event-service
          uri: http://event_service:8080/
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=0
            
        - id: review-service
          uri: http://user_service:8000/
          predicates:
            - Path=/api/reviews/**
          filters:
            - RewritePath=/api/reviews/(?<segment>.*), /api/review/$\{segment}
            
        # Авторизация через user-service
        - id: auth-service
          uri: http://user_service:8000/
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}
  main:
    web-application-type: reactive

# Настройки JWT
jwt:
  secret: ${JWT_SECRET:SecretKey}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always