apiVersion: batch/v1
kind: CronJob
metadata:
  name: kafka-message-sender
spec:
  # Выполнение задачи каждые 12 часов: в 00:00 и в 12:00
  schedule: "0 0,12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kafka-producer
              image: confluentinc/cp-kafka:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - |
                  echo 'startOpera' | kafka-console-producer --broker-list kafka-service:29092 --topic parsing
          restartPolicy: OnFailure
