apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.17
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-service:9200"  # имя сервиса Elasticsearch
        ports:
        - containerPort: 5601
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.2"    # снижено с 250m
          limits:
            memory: "512Mi"
            cpu: "0.3"    # снижено с 500m