apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser-service
  template:
    metadata:
      labels:
        app: parser-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: parser-service
        image: ghcr.io/securitytrip/parser-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "30m"
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:29092"
        - name: MONGO_URI
          value: "mongodb://admin:admin123@mongodb-service:27017"
        - name: GROUP_ID
          value: "1"
        - name: TOPIC
          value: "parsing"