apiVersion: v1
kind: ConfigMap
metadata:
  name: parser-service-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "afisha"
  KAFKA_BROKER: "kafka-service:29092"
  TOPIC: "parsing"
  GROUP_ID: "1" 