apiVersion: v1
kind: Service
metadata:
  name: parser-service
  labels:
    app: parser-service
spec:
  selector:
    app: parser-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 