apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-calculator
  template:
    metadata:
      labels:
        app: rate-calculator
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: rate-calculator
        image: ghcr.io/securitytrip/rate-calculator:latest
        resources:
          limits:
            cpu: "0.2"
            memory: "150Mi"
          requests:
            cpu: "0.1"
            memory: "75Mi"
        env:
        - name: KAFKA_BROKERS
          value: "kafka-1-service:29092,kafka-2-service:29093"
        - name: KAFKA_TOPIC
          value: "product_rating_update"
        - name: PG_CONN_STR
          value: "dbname=afisha_db user=admin password=admin123 host=postgres-service"