apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utils-service
  template:
    metadata:
      labels:
        app: utils-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: utils-service
        image: ghcr.io/securitytrip/utils-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8182
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:29092"
        - name: TOPIC
          value: "parsing"