apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utils-service
  template:
    metadata:
      labels:
        app: utils-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: utils-service
        image: ghcr.io/securitytrip/utils-service:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
          requests:
            cpu: "0.05"
            memory: "64Mi"
        ports:
        - containerPort: 8182
        env:
        - name: KAFKA_BROKER
          value: "kafka-1-service:29092"
        - name: TOPIC
          value: "parsing"