name: Build and Push Docker Images to Personal ghcr.io

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: SecurityTrip
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          for dir in $(find . -name 'Dockerfile' -exec dirname {} \;); do
            image_name=$(basename $dir)
            docker build -t ghcr.io/<your-username>/$image_name:latest $dir
            docker push ghcr.io/<your-username>/$image_name:latest
          done
